### ISSUE TITLE
not being able to install after update to HA 2021.6

### ISSUE THREAD

**Issue by kodbeeck** [filipvh/hass-nhc2#22]
Hello, I have been using the nhc2 integration for a few months now and everything worked very good. After updating to 2021.6 the niko integration did not load, and I deleted the old integrations, updated the package to the latest version that contains the fix and tried reinstalling. However the installation takes forever and doesn't seem to do anything.  All I can do is eventually refresh the page and nothing is installed.

**Comment by anvarit** [comment]
what errors do you have in HA log?

**Comment by filipvh** [comment]
If this is not resolved by next week, I might find the time to test with the latest HA.
I hope someone can help you earlier that that :(

**Comment by kodbeeck** [comment]
Hi,
Thanks for the replies!
I do not see any errors in the log regarding nhc2. When trying to add the integration, nothing happens and I only see a spinning circle. Other integrations do install. I tried several browsers, rebooting, clear cache etc

Steps i did:
Upgraded to latest version of HA 2021.6.5
deleted old nhc2 installation, as it was not loading
Installed new nhc2 version through HACS
rebooted the machine
Tried installing new nhc2 version and nothing happens.

Hope this helps a bit.

**Comment by davidkinders** [comment]
Same problem here, new install nog errors in log. 
when adding the integration in keeps showing with turning wheel “please wait while installing”
![1FE8AAAB-0EC0-4A4E-92A6-8C5950F59EC4](https://user-images.githubusercontent.com/11700819/122857672-21d23700-d319-11eb-954c-9531ba51f559.png)

**Comment by filipvh** [comment]
I upgraded today, without issue. First hacs and hass-nhc2, then HA.
I haven't installed a new 'nhc2' integration, so I'll try to setup a 2nd setup to test this.

**Comment by filipvh** [comment]
Btw, to see something is the logs, you might want to enable logging on custom components or hass-nhc2 specific.
see [https://www.home-assistant.io/integrations/logger/](https://www.home-assistant.io/integrations/logger/) for details
I've got mine setup like this:
```yaml
logger:
  default: warning
  logs:
    custom_components: debug
```

**Comment by kodbeeck** [comment]
Hi Filip,

Thanks for trying to replicate the problem. I enabled logging of custom_components, as suggested.  However, still nothing in the logs. It looks like it doesn't even try to install. It does show the spinning blue circle, but that keeps spinning indefinitely.

**Comment by filipvh** [comment]
@kodbeeck I assume you restarted HA after that config change 😄 
I hope I get more lucky in finding the issue.
You do have the latest HA I hope? So we have similar results.
I'm on HA core-2021.6.6
In a previous post you mention core-2021.6.5

**Comment by nielsvissers** [comment]
i'm having the same problems
i'm trying to rebuild the custom component from scratch to see where the problem is

**Comment by 2Fast2BCn** [comment]
I have the same problem.
Might this be related?
https://community.home-assistant.io/t/hacs-installing-problem-via-integration-error-config-flow-could-not-be-loaded/314501

**Comment by Tjaardv** [comment]
Same here

installed version 1.0.0 update to 1.6.0 
Reboot server 
installation succeeded

**Comment by 2Fast2BCn** [comment]
I cannot get this to work.
I even purchased an Odroid N2+ thinking it would be better but no luck.
If I add:

````
nhc2:
  host: '192.168.0.196'
  port: 8883
  username: hobby
  password: password
````

Then it's visible in the integrations page but nothing is happening.
There is nothing in the logs as far as I can find.

**Comment by nielsvissers** [comment]
have you tried a restart of the host?
not just home assistant?

**Comment by 2Fast2BCn** [comment]
At least 10 times already ;-)
ha core rebuild
full system reboot
reinstall
install 1.0.0 (but then you cannot add the integration and it doesn't recognize nhc2 in the configuration file?)
is there a way to show more logging
I currently have the advised
````
logger:
  default: info
  logs:
    custom_components.hacs: debug
    hacs: debug
    queueman: debug
    AIOGitHubAPI: debug
````

**Comment by nielsvissers** [comment]
first install v1.0.0, reboot, upgrade to v1.6.0, reboot
then it should work

**Comment by 2Fast2BCn** [comment]
I installed 1.0.0
logs show
````
ERROR (SyncWorker_1) [homeassistant.loader] The custom integration 'nhc2' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details
````
then I did full system reboot (same error is shown in the logs which is normal I guess)
then I updated to 1.6.0
then I did full system reboot
then the logs show:
````
2021-07-14 17:29:52 DEBUG (MainThread) [custom_components.nhc2] Connecting to 192.168.0.198 with hobby
````
nothing else is happening no entities are registered nothing in the logs
trying to add the integration via the GUI results in the long running "Installation of the integration" resulting in the "config flow" error with nothing in the logs.

**Comment by Murray112** [comment]
Same problem here...
Tried with all the versions via hacs or manually, puting de folder inside custom_components. Update is done but it is impossible to add the integration. The never ending spinning wheel stays there.

I hope a fix will be found for this issue.
Anyways, I want to thank the developer because its a great addon. I use it since several months and I hope it will be available again pretty soon

**Comment by 2Fast2BCn** [comment]
I think other add-ons have the same problem https://community.home-assistant.io/t/hacs-installing-problem-via-integration-error-config-flow-could-not-be-loaded/

**Comment by joleys** [comment]
It might be related to the 'external_url'.  Please read [https://github.com/home-assistant/core/issues/47449](https://github.com/home-assistant/core/issues/47449).

**Comment by Murray112** [comment]
No changes with the las HA update. Still stuck in the spinning wheel and I see that other users have the same issue.
I have reviewed for the external url and in my case it doesn't change. 
Have you tested to do a fresh install of NHC2 in the new version of HA? I wonder if all systems are affected with the new version or there are personal config elements conditioning this situation.

**Comment by nielsvissers** [comment]
in the logs i see next entry
`2021-07-25 13:43:50 DEBUG (MainThread) [custom_components.hacs] <Integration filipvh/hass-nhc2> Running checks against 1.6.0
`
but not "checks passed"
maybe the initialization isn't complete?

**Comment by nielsvissers** [comment]
found the issue
inside repository nhc2-coco the "done" function is never called because the function "_done_discovering_profiles_callback" is called too soon.
adding a while loop with a sleep fixed it on my installation

i'll try to make a pull request in the other repo soon

**Comment by Murray112** [comment]
Hi all, I've retested a fresh install with the new Ha update 2021.08 without luck.. I wonder if there are some news about the possible fix to the installation problem.

Thank you very much,

**Comment by nielsvissers** [comment]
I'm on holiday at the moment. I'll create pull requests when home. Verzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: Murray112 ***@***.***> Datum: 5/08/2021  14:20  (GMT+01:00) Aan: filipvh/hass-nhc2 ***@***.***> Cc: nielsvissers ***@***.***>, Comment ***@***.***> Onderwerp: Re: [filipvh/hass-nhc2] not being able to install after update to HA 2021.6 (#22) 
Hi all, I've retested a fresh install with the new Ha update 2021.08 without luck.. I wonder if there are some news about the possible fix to the installation problem.
Thank you very much,

**Comment by minosrex** [comment]
Any news on this? My Niko lights still don't work in HA... Thanks.

**Comment by fierske** [comment]
Hello,

I am running HA on my NAS and it would be nice if I could integrate NHC2 with it. I tried everything so far but the intigration keeps on spinning. Is there already an update when this will be working again?

Thank you in advanced.

**Comment by p8ulus** [comment]
Home assistant 2021.10.2
hass-nhc-1.7.0-beta1

Same problem here, new install no errors in log.
when adding the integration in keeps showing with turning wheel “please wait while installing”

logboek 2021-10-09 09:23:16 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nhc2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

**Comment by p8ulus** [comment]
> 
> 
> Same problem here, new install no errors in log. when adding the integration in keeps showing with turning wheel “please wait while installing” ![1FE8AAAB-0EC0-4A4E-92A6-8C5950F59EC4](https://user-images.githubusercontent.com/11700819/122857672-21d23700-d319-11eb-954c-9531ba51f559.png)

Same problem here

**Comment by p8ulus** [comment]
![config map](https://user-images.githubusercontent.com/45506094/136655057-77ae7ffa-c66a-4254-b724-3a5b67a6b611.jpg)
![nhc2](https://user-images.githubusercontent.com/45506094/136655063-3aecce91-71a7-48af-a409-52a990d55bd5.jpg)

**Comment by LinoxBE** [comment]
@nielsvissers any update regarding the update? Anything I can do to help?

I have he same issue, with the nhc2 install that is hanging, on my new HA setup.

**Comment by nielsvissers** [comment]
this is correct

**Comment by LinoxBE** [comment]
I did the same as @davidkinders and it worked for me too. Thank you very much for this!

**Comment by minosrex** [comment]
I suppose this means you manually install nhc2-coco? Since my HA runs on in a container in Synology NAS, I would have to install it inside the docker. Can this be done?

**Comment by nielsvissers** [comment]
It can be done but I think you will have to redo this with every upgrade of HA because the docker is being rebuilt then.You'll have to install the terminal add-on i thinkVerzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: minosrex ***@***.***> Datum: 30/10/2021  09:10  (GMT+01:00) Aan: filipvh/hass-nhc2 ***@***.***> Cc: nielsvissers ***@***.***>, Mention ***@***.***> Onderwerp: Re: [filipvh/hass-nhc2] not being able to install after update to HA 2021.6 (#22) 
I suppose this means you manually install nhc2-coco? Since my HA runs on in a container in Synology NAS, I would have to install it inside the docker. Can this be done?

**Comment by minosrex** [comment]
That's what I thought, reinstall with every new version with HA. So a temporary fix at most. Still supporting a 'real' solution!

**Comment by LinoxBE** [comment]
You can actually create a Docker file, which will use the HA container and
let Docker automatically do the pip install for you.

That's how containers work. Not sure how this works with your setup and the
container version of HA.

Op za 30 okt. 2021 09:10 schreef minosrex ***@***.***>:

**Comment by geertmeersman** [comment]
@davidkinders I did the same,  all went fine, but I still don't have entities from Niko showing up.
And  no errors in the logbook... something  missing on my side?

**Comment by davidkinders** [comment]
Hallo @geertmeersman great that this worked for u. 

Which entities are not showing, switches and sensors are not implanted at this moment.

**Comment by minosrex** [comment]
I found that the Synology docker container has a terminal window, so I tried to manually install nhc2-coco using the commands above. However, I got the same error messages as HA itself gives me upon trying to import the library. The issue seems to be with the netifaces package:

"Unable to install package nhc2-coco==1.4.1: ERROR: Command errored out with exit status 1: command: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cy8kvopu/netifaces/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cy8kvopu/netifaces/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-3rcg7jfv cwd: /tmp/pip-install-cy8kvopu/netifaces/ Complete output (19 lines): running bdist_wheel running build running build_ext checking for getifaddrs...found. checking for getnameinfo...found. checking for IPv6 socket IOCTLs...not found. checking for optional header files...netpacket/packet.h. checking whether struct sockaddr has a length field...no. checking which sockaddr_xxx structs are defined...in in6 un ll. checking for routing socket support...no. checking for sysctl(CTL_NET...) support...no. checking for netlink support...no. building 'netifaces' extension gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fno-semantic-interposition -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -DTHREAD_STACK_SIZE=0x100000 -fPIC -DNETIFACES_VERSION=0.10.9 -DHAVE_GETIFADDRS=1 -DHAVE_GETNAMEINFO=1 -DHAVE_NETPACKET_PACKET_H=1 -DHAVE_SOCKADDR_IN=1 -DHAVE_SOCKADDR_IN6=1 -DHAVE_SOCKADDR_UN=1 -DHAVE_SOCKADDR_LL=1 -I/usr/local/include/python3.9 -c netifaces.c -o build/temp.linux-x86_64-3.9/netifaces.o netifaces.c:131:14: fatal error: linux/tipc.h: No such file or directory 131 | # include <linux/tipc.h> | ^~~~~~~~~~~~~~ compilation terminated. error: command '/usr/bin/gcc' failed with exit code 1 ---------------------------------------- ERROR: Failed building wheel for netifaces ERROR: Command errored out with exit status 1: command: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cy8kvopu/netifaces/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cy8kvopu/netifaces/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-m8tv7oys/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/netifaces cwd: /tmp/pip-install-cy8kvopu/netifaces/ Complete output (19 lines): running install running build running build_ext checking for getifaddrs...found. checking for getnameinfo...found. checking for IPv6 socket IOCTLs...not found. checking for optional header files...netpacket/packet.h. checking whether struct sockaddr has a length field...no. checking which sockaddr_xxx structs are defined...in in6 un ll. checking for routing socket support...no. checking for sysctl(CTL_NET...) support...no. checking for netlink support...no. building 'netifaces' extension gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fno-semantic-interposition -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -DTHREAD_STACK_SIZE=0x100000 -fPIC -DNETIFACES_VERSION=0.10.9 -DHAVE_GETIFADDRS=1 -DHAVE_GETNAMEINFO=1 -DHAVE_NETPACKET_PACKET_H=1 -DHAVE_SOCKADDR_IN=1 -DHAVE_SOCKADDR_IN6=1 -DHAVE_SOCKADDR_UN=1 -DHAVE_SOCKADDR_LL=1 -I/usr/local/include/python3.9 -c netifaces.c -o build/temp.linux-x86_64-3.9/netifaces.o netifaces.c:131:14: fatal error: linux/tipc.h: No such file or directory 131 | # include <linux/tipc.h> | ^~~~~~~~~~~~~~ compilation terminated. error: command '/usr/bin/gcc' failed with exit code 1 ---------------------------------------- ERROR: Command errored out with exit status 1: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cy8kvopu/netifaces/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cy8kvopu/netifaces/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-m8tv7oys/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/netifaces Check the logs for full command output. WARNING: You are using pip version 20.2.4; however, version 21.3.1 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command."

**Comment by geertmeersman** [comment]
> Which entities are not showing, switches and sensors are not implanted at this moment.

@davidkinders even the lights, I have no entities at all showing  up :-(

**Comment by geertmeersman** [comment]
Hi @minosrex , you need to install the headers too:

apk add libffi-dev

**Comment by minosrex** [comment]
That did the trick, thanks Geert! Now if the custom component would do the same, then it will continue to run when HA updates.

**Comment by p8ulus** [comment]
> 
> 
> I got it finaly working.
> 
> TAKE A BACKUP!!!!
> 
> Open a terminal. apk add build-base apk add alpine-sdk linux-headers libffi-dev apk add python3-dev pip3 install nhc2-coco
> 
> Add this to your configuration.yaml nhc2: host: 0.0.0.0 port: 8884 username: "hobby" password: your key
> 
> regards David
![integration nhc2 not found](https://user-images.githubusercontent.com/45506094/139637171-c3e61085-25d4-439a-a6ca-6c90119c92e3.jpg)

when I enter the above lines in the terminal and click on "check configuration" I get the message integration nhc2 not found

**Comment by p8ulus** [comment]
![Naamloos](https://user-images.githubusercontent.com/45506094/139637709-4d49e6aa-6fb5-40c4-b0ed-c3f01d88452a.jpg)

**Comment by joleys** [comment]
@p8ulus
Your username and password is not 'hobby' and the API Token.  The alternative way to connect with a profile uses port 8883.

**Comment by tommeysen** [comment]
Hi, I'm having the same issue. However I'm not able to solve this.
To my understanding, what is the difference between this nhc2 project and the nhc2-coco variant which seem to be proposed here as well?
I tried to install nhc through HACS as well, but also stays loading for hours. 

Thanks for all the suggestions already.

**Comment by joleys** [comment]
Hass-nhc2 is the main integration for Home Assistant, which relies on nhc2-coco as dependency to provide communication with the NHCII controller.  In other words: nhc2-coco knows how to communicate with your Niko installation and hass-nhc2 translates this knowledge into HA compatible entities, functions and variables.

If you install hass-nhc2 it will (or at least: should) install nhc2-coco in the background.  From other replies in this discussion it seems this sometimes goes wrong.

**Comment by tommeysen** [comment]
@joleys thanks for your reply, that clears it all up to me!

The problem I'm still having right now is that I'm unable to install hass-nhc2 on Home Assistant again (always used it in the past, but due to issues thought reinstalling it was the best idea to solve it).
I tried to install it, by adding those required files manually on my home assistand and then installing it through the integrations. But Also tried it via HACS and then via integrations, but both give the same result being that my screen stays stuck and loading at "please wait while Niko Home Control II is being setup".

Does anyone still has any suggestions on how to solve this?
I also tried the suggestion from David, being:
"
Open a terminal.
apk add build-base
apk add alpine-sdk linux-headers libffi-dev
apk add python3-dev
pip3 install nhc2-coco

Add this to your configuration.yaml
nhc2:
host: 0.0.0.0
port: 8884
username: "hobby"
password: your key
"

But was also not able to get the integration installed then, and my Home Assistant system was very slow afterwards as well so had to restore it to the backup I took before.

**Comment by p8ulus** [comment]
homeassistant reinstalled updated to latest version, above description performed.
Open a terminal.
apk add build base
apk add alpine-sdk linux-headers libffi-dev
apk add python3-dev
pip3 install nhc2-coco

Add this to your configuration.yaml
nhc2:
host: 0.0.0.0
postage: 8884
username: "hobby"
password: your key

I still get the same message "Unable to load config flow"

**Comment by sebakerckhof** [comment]
For me the steps above also didn't work

**Comment by Gavergracht** [comment]
any progress here ?

**Comment by williammorren** [comment]
I've got the same issue, any updates?

**Comment by minosrex** [comment]
For me, the solution of David Kinders (29 Oct) combined with Geert Meersman (31 Oct) on installing the headers, got it to work, which it does until today. However, I do not want to install a new version of HA because this will mess up the integration again. Niels, any view on a permanent fix?

**Comment by fierske** [comment]
Hello, 

I had a worked NHC2 with above steps. I added some rest_commands in my configuration.yaml
After rebooting HA to activate the rest_commads I get a error on my NHC2? I didn't changed anything on the parameters of NHC2. Error: not authorized? Can you only make one connection for a specific time? Someone an idea what's wrong?

Kind regards,
Dirk

Logger: root
Source: /usr/src/homeassistant/homeassistant/bootstrap.py:315
First occurred: 16:18:08 (1 occurrences)
Last logged: 16:18:08

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3452, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2942, in _packet_handle
    return self._handle_connack()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3029, in _handle_connack
    self.on_connect(
  File "/usr/local/lib/python3.9/site-packages/nhc2_coco/coco.py", line 118, in _on_connect
    raise Exception(MQTT_RC_CODES[rc])
Exception: Connection refused - not authorised

**Comment by fierske** [comment]
> Hello,
> 
> I had a worked NHC2 with above steps. I added some rest_commands in my configuration.yaml After rebooting HA to activate the rest_commads I get a error on my NHC2? I didn't changed anything on the parameters of NHC2. Error: not authorized? Can you only make one connection for a specific time? Someone an idea what's wrong?
> 
> Kind regards, Dirk
> 

FYI

I have installed the new HA 7.2 and reinstalled NHC2 and now everything works fine again.

**Comment by Murray112** [comment]
I've finally succeded to have the integration installed but I would like to know how to resolve the Niko problem to get the api token.

{"answer"=<the answer to Life, The Universe and Everything Else>} 

I know the answer but no the correct JSOn syntax.

Can you help me to solve it? thanks again.

Lot of brainstorming to controle our lights from home assistant...

I will give a feedback if it works when pasted it. ;)

**Comment by pdemeyer** [comment]
{answer:42} should work

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Murray112 ***@***.***>
Verzonden: Saturday, January 29, 2022 9:29:48 PM
Aan: filipvh/hass-nhc2 ***@***.***>
CC: pdemeyer ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [filipvh/hass-nhc2] not being able to install after update to HA 2021.6 (#22)


I've finally succeded to have the integration installed but I would like to know how to resolve the Niko problem to get the api token.

{"answer"=<the answer to Life, The Universe and Everything Else>}

I know the answer but no the correct JSOn syntax.

Can you help me to solve it? thanks again.

Lot of brainstorming to controle our lights from home assistant...

I will give a feedback if it works when pasted it. ;)

**Comment by Murray112** [comment]
Tried but it doesn't work. It asks to correct the syntax of the whole phrase. I've tried also replacing answer by 42 but it doesn't work.
Any ideas?

**Comment by joleys** [comment]
> Tried but it doesn't work. It asks to correct the syntax of the whole phrase. I've tried also replacing answer by 42 but it doesn't work.
> Any ideas?

Did you notice the small difference of ‘:’ versus ‘=‘?

**Comment by Murray112** [comment]
![image](https://user-images.githubusercontent.com/76228877/151745685-eb5c55c8-3ff3-48eb-9e07-c72fccf9da16.png)
I've tried several combinations .
{answer:42} too. 
But it seems to be still wrong in my case. I miss something..

**Comment by geertmeersman** [comment]
JSON syntax

{"answer":42}

Cheers,
Geert

Op ma 31 jan. 2022 06:57 schreef Murray112 ***@***.***>:

**Comment by LinoxBE** [comment]
The correct answer to get your API token is actually:

*{"answer"='The answer to Life, The Universe and Everything Else'}*

Always worked for me, every time.


Fred

**Comment by Murray112** [comment]
I've tried...

*{"answer"='The answer to Life, The Universe and Everything Else'}*
{"answer"='The answer to Life, The Universe and Everything Else'}
{"42"='The answer to Life, The Universe and Everything Else'}
*{"42"='The answer to Life, The Universe and Everything Else'}*


But it still saying that my JSON is wrong...

Can you retry to see if it works for you?

Thanks again for yout help,

Fernando

**Comment by sebakerckhof** [comment]
@Murray112 enter exactly what geert posted above. What you posted isn't valid json.

**Comment by Murray112** [comment]
Thank you all!! 
I probably did a bad manipulation last day. I've retested Geert's answer and now it worked! I have my API token.
The problem now... is that I have no entities showing at the integrations page. I have the Niko integration with no entities. I'm using Geerts config:

```
nhc2: 
  host: Niko Hub IP
  port: 8884 
  username: hobby
  password: API token
```

I've tried putting "" to the username and pass also but nothing.

It's probably a silly thing but I can' get it finally working...

Thanks for your patience again ;)



Murray

**Comment by Murray112** [comment]
Little up! 

After succesfully added the integration and the Holy API Token, I can't see any of my Niko ligths or sensors...
Have you found any solution for this? Even temporary to renew each HA update.
@geertmeersman @sebakerckhof ?

Thanks a lot.

Murray_

**Comment by spaceman569** [comment]
Hi All,

I've successfully installed the NHC2 integration via HACS, solved the Hobby API question to get access to my password, added the nhc2: lines in the configuration.yaml, rebooted HA, all this in various combinations but I still don't get any entities from the nhc2 integration. I wonder, is this working for anyone out there or should I give up trying?

Thanks,
Thomas

**Comment by minosrex** [comment]
Hi spaceman569, what does the log say when you start up?
I had to manually install the NHC2 Coco repository because it is needed and does not come with HA. Above, some nice people explained me how to do it. See: https://github.com/filipvh/hass-nhc2/issues/22#issuecomment-955678809. Since I am running HA in a Docker on my Synology NAS, I had to execute these commands within that docker's terminal window -and I will have to re-do them for every installation of HA until someone integrates this update in HA. (I lack the skill to do this)

This worked for a while, but then stopped as well because you there was a dependencies issue. People solved it here: https://github.com/filipvh/hass-nhc2/issues/38. I myself managed to solve it by forcing the installation of the right version.

**Comment by spaceman569** [comment]
Hi minosrex,

massive thanks for pointing me in the right direction. I thought this thread would not help me since I couldn’t see a clear working conclusion. However, tonight I got it to work by executing #22 and then #38, but since I have a fresh HA installation on a RPi I believe I could have merged the two instead of doing them in sequence (?).

I still have one question; I see only switches and lights not virtual devices/outputs, mini pirs nor scenarios that I have in Niko. Do you know how to add them manually?

**Comment by minosrex** [comment]
Hi spaceman569, I never implemented anything within Niko beyond the electrician defining the lights when he did the installation. I had it installed with HA in mind -which is why I hope it keeps working!

**Comment by geertmeersman** [comment]
Hi, I have seen in the hobby api documentation that quite some features are possible to extract/interact with.
[https://mynikohomecontrol.niko.eu/Content/hobbyapi/documentation.pdf](https://mynikohomecontrol.niko.eu/Content/hobbyapi/documentation.pdf)

Also the PIR (@spaceman569) :
![image](https://user-images.githubusercontent.com/1844091/170957194-45a0e450-4076-4a01-a052-dd84d102f1a1.png)

My proposal would be to add them to the addon, you could already play with it using an MQTT client, this is how I debugged things.

**Comment by spaceman569** [comment]
Hi geertmeersman, this looks interesting, thanks! I am aware of the documentation but haven't dug into it yet... it will probably take some time (family first :) ) before I see the Niko PIRs in HA. Maybe I go for the simpler solution and install parallel HW (PIRs or door switches) directly to HA. Not a sexy solution, but very fast. I'll post here if I go the long way through nhc2.

**Comment by nielsvissers** [comment]
As far as i have seen, there is a difference between the json data for pir Action and normal button Actions. A pir is more a scene than a button. If the scenes are integrated so wil pir or vice versaVerzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: spaceman569 ***@***.***> Datum: 4/06/2022  09:29  (GMT+01:00) Aan: filipvh/hass-nhc2 ***@***.***> Cc: nielsvissers ***@***.***>, Mention ***@***.***> Onderwerp: Re: [filipvh/hass-nhc2] not being able to install after update to HA 2021.6 (#22) 
Hi geertmeersman, this looks interesting, thanks! I am aware of the documentation but haven't dug into it yet... it will probably take some time (family first :) ) before I see the Niko PIRs in HA. Maybe I go for the simpler solution and install parallel HW (PIRs or door switches) directly to HA. Not a sexy solution, but very fast. I'll post here if I go the long way through nhc2.

**Comment by spaceman569** [comment]
OK, that is also an interesting piece in the puzzle. I am missing the scenes as well so maybe I should focus on those and hopefully the PIRs will come automatically. I plan to spend some time on this in July, during my vacation on rainy days :).

**Comment by nielsvissers** [comment]
a default pir scene apparently doesn't send out a MQTT event when triggerd.
i have the generic routines available but not in this project
this one has been abandoned and is continued on https://github.com/joleys/niko-home-control-II
