### ISSUE TITLE
custom component breaks on 0.118

### ISSUE THREAD

**Issue by sverleysen** [filipvh/hass-nhc2#4]
When I update HA to 0.118 only the first action works from HA. After that the integration seems to stop working.
When I do a reboot, only the first action works again.

After a downgrade to 0.117.6 everything seems to work like normal again.

**Comment by filipvh** [comment]
@sverleysen I'll check it out

**Comment by filipvh** [comment]
It does seem to work here @sverleysen 
BUT I must warn you
I've removed PORT from the configuration
you should too

Also, you can actually remove the configuration from configuration.yaml,
restart the server, and then, add is using the UI (see new readme)
It should be easy (if you know the profiles password)

**Comment by sverleysen** [comment]
I'll try again without the PORT

**Comment by filipvh** [comment]
@sverleysen sorry, will be reintroducing port, did not know hobby api used other port, need to support this... 🤦

**Comment by sverleysen** [comment]
Without PORT it doesn't work.
I can't add it using the UI, I don't see the integration in the list.

**Comment by sverleysen** [comment]
I missed there was a new release. I installed it: now the PORT is indeed invalid and I can connect using the UI.
But my main issue remains. Only the first action worked

**Comment by filipvh** [comment]
do you have some logs that might help me?

**Comment by sverleysen** [comment]
`2020-11-19 15:10:59 ERROR (Thread-116) [root] Uncaught thread exception
Traceback (most recent call last):
File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.8/threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3452, in _thread_main
self.loop_forever(retry_first_connection=True)
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
rc = self.loop(timeout, max_packets)
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1181, in loop
rc = self.loop_read(max_packets)
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1572, in loop_read
rc = self._packet_read()
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
rc = self._packet_handle()
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2936, in _packet_handle
return self._handle_publish()
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3220, in _handle_publish
self._handle_on_message(message)
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3444, in _handle_on_message
self.on_message(self, self._userdata, message)
File "/usr/local/lib/python3.8/site-packages/nhc2_coco/coco.py", line 110, in _on_message
self._device_callbacks[device['Uuid']]['callbackHolder'](device)
TypeError: 'NoneType' object is not callable`

This only logs 1 time, after that no logging.

**Comment by sverleysen** [comment]
I also updated to the latest release of the component, but the issue remains.

**Comment by filipvh** [comment]
@sverleysen 
Should be resloved now (new release) 
If you are able to join on: https://join.slack.com/t/newworkspace-xgi8370/shared_invite/zt-j6qy16sl-kZF6V__uTCLVLpZUNutJWA
trying to centralise the ongoing effort there 😃

**Comment by filipvh** [comment]
Resolved through chat
