### ISSUE TITLE
Cannot install NHC2 on fresh install

### ISSUE THREAD

**Issue by nexus256** [filipvh/hass-nhc2#45]
Hi,

I'm trying to move my HASS installation from RPI to VMWare (fresh installation)
Core Version: core-2022.3.0
Operating System: Home Assistant OS 7.4

This error originated from a custom integration.

Logger: root
Source: custom_components/nhc2/coco_discover_profiles.py:58
Integration: Niko Home Control II (documentation, issues)
First occurred: 14:22:11 (1 occurrences)
Last logged: 14:22:11

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/config/custom_components/nhc2/coco_discover.py", line 61, in _scan_for_nhc
    self._on_done()
  File "/config/custom_components/nhc2/coco_discover_profiles.py", line 53, in _done_discovering_controllers_callback
    CoCoProfiles(self._discover_profiles_callback(ctrl[0], ctrl[1]), ctrl[0],
  File "/config/custom_components/nhc2/coco_profiles.py", line 37, in __init__
    self._done_discovering_profiles_callback()
  File "/config/custom_components/nhc2/coco_discover_profiles.py", line 58, in _done_discovering_profiles_callback
    time.sleep(1)
NameError: name 'time' is not defined

The error above received when nothing is added to configuration.yaml.  Also tried to reboot HASS & Niko home controller bus system entirely.

If I add host (IP address), username ("hobby"), port (8884) and password ("from Niko api website"), I'm able to read all entities but they are not updating.  After rebooting both systems (HASS & Niko home controller bus system) all entities are unavailable.

**Comment by dimitridelanghe** [comment]
@nexus256 is this still an issue or after the updates its ok?
otherwise close the issue please!
