### ISSUE TITLE
Seems like latest update of the controller throws errors in the integration

### ISSUE THREAD

**Issue by stijnpiron** [filipvh/hass-nhc2#55]
I just updated my controller to v2.17.1.521 and now the integration seems to be broken. Getting these errors in the log:

```
Logger: homeassistant.config_entries
Source: helpers/entity_component.py:169
First occurred: 09:37:59 (15 occurrences)
Last logged: 09:37:59

Error setting up entry hobby (FP00112A22471A.home) for number
Error setting up entry hobby (FP00112A22471A.home) for select
Error setting up entry hobby (FP00112A22471A.home) for sensor
Error setting up entry hobby (FP00112A22471A.home) for switch
Error setting up entry hobby (FP00112A22471A.home) for update
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/alarm_control_panel/__init__.py", line 115, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 169, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
```
The error list is longer, just copied the first couple of entries.

**Comment by stijnpiron** [comment]
too soon, a restart of HA seems to fix it...
